language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - 10 # current
  - 8  # lts

cache:
  yarn: true

# Travis currently has built-in yarn@1.3.2 on linux
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
